<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BurnSoft.Universal</RootNamespace>
    <AssemblyName>BurnSoft.Universal</AssemblyName>
    <AssemblyVersion>4.1.33.6</AssemblyVersion>
    <FileVersion>4.1.33.6</FileVersion>
    <Description>Contains a bunch of classes that we use for our applications.</Description>
    <Copyright>Copyright © BurnSoft 2013 - 2025</Copyright>
    <Authors>www.burnsoft.net</Authors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>C:\Source\Repos\BurnSoft.Universal\BurnSoft.Universal\bin\Debug\net8\</OutputPath>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <DocumentationFile>BurnSoft.Universal.xml</DocumentationFile>
  </PropertyGroup>
  
  <PropertyGroup>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon />
    <StartupObject />
    <Title>$(AssemblyName)</Title>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>BurnSoft.Universal.xml</DocumentationFile>
    <OutputPath>C:\Source\Repos\BurnSoft.Universal\BurnSoft.Universal\bin\Release\net8\</OutputPath>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\BurnSoft.Universal\BSActiveDirectory.vb" Link="BSActiveDirectory.vb" />
    <Compile Include="..\BurnSoft.Universal\BSDateTime.vb" Link="BSDateTime.vb" />
    <Compile Include="..\BurnSoft.Universal\BSEncryption.vb" Link="BSEncryption.vb" />
    <Compile Include="..\BurnSoft.Universal\BSFileSystem.vb" Link="BSFileSystem.vb" />
    <Compile Include="..\BurnSoft.Universal\BSMath.vb" Link="BSMath.vb" />
    <Compile Include="..\BurnSoft.Universal\BSNetwork.vb" Link="BSNetwork.vb" />
    <Compile Include="..\BurnSoft.Universal\BSOtherObjects.vb" Link="BSOtherObjects.vb" />
    <Compile Include="..\BurnSoft.Universal\BSProcessInfo.vb" Link="BSProcessInfo.vb" />
    <Compile Include="..\BurnSoft.Universal\BSRegistry.vb" Link="BSRegistry.vb" />
    <Compile Include="..\BurnSoft.Universal\BSSystemInfo.vb" Link="BSSystemInfo.vb" />
    <Compile Include="..\BurnSoft.Universal\BSWebResponse.vb" Link="BSWebResponse.vb" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.DirectoryServices" Version="9.0.9" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.9" />
    <PackageReference Include="System.Management" Version="9.0.9" />
  </ItemGroup>

</Project>
